PROJECT_NAME = LLVM-TEST
PROJ_VERSION = 3.1svn
#
# Set this variable to the top of the LLVM source tree.
#
LLVM_SRC_ROOT = /home/dan/projects/TaintTracking/llvm

#
# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
#
LLVM_OBJ_ROOT = /home/dan/projects/TaintTracking/llvm

# Set this variable based on whether or not we have access to LLVM source and
# object trees.
ifeq ($(LLVM_SRC_ROOT),no)
HAS_LLVM := 0
else
ifeq ($(LLVM_OBJ_ROOT),no)
HAS_LLVM := 0
else
HAS_LLVM := 1
endif
endif

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(subst //,/,/home/dan/projects/TaintTracking/llvm/projects/test-suite)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,/home/dan/projects/TaintTracking/llvm/projects/test-suite)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /usr/local

# Include LLVM's configuration Makefile, if available.
ifeq ($(HAS_LLVM),1)
include $(LLVM_OBJ_ROOT)/Makefile.config
else

# Otherwise, define specific things we know we need.
realpath = $(shell cd $(1); $(PWD))
PROJ_OBJ_DIR  := $(call realpath, .)
PROJ_OBJ_ROOT := $(call realpath, $(PROJ_OBJ_DIR)/$(LEVEL))
PROJ_SRC_DIR := $(call realpath, $(PROJ_SRC_ROOT)/$(patsubst $(PROJ_OBJ_ROOT)%,%,$(PROJ_OBJ_DIR)))

CP := cp
DATE := date
DOT := dot
ECHO := echo
INSTALL := install
LIBS :=
MKDIR := mkdir
MV := mv
PWD := pwd
RM := rm
SED := sed
TCLSH := tclsh

# Configure parameters.
TARGET_OS := Linux
ARCH := x86_64
ENDIAN := little

endif

# Ignore the LIBS set by $(LLVM_OBJ_ROOT)/Makefile.config
LIBS :=

# Set SourceDir for backwards compatibility.
ifndef SourceDir
SourceDir=$(PROJ_SRC_DIR)
endif

ORIGINAL_CC := $(CC)
ORIGINAL_CXX := $(CC)

ifdef TARGET_ARCH
ARCH := $(TARGET_ARCH)
endif

ifdef TARGET_CC
CC := $(TARGET_CC)
endif

ifdef TARGET_CXX
CXX := $(TARGET_CXX)
endif

# Path to location for LLVM C/C++ front-end. You can modify this if you
# want to override the value set by configure.
LLVMGCCDIR := 

# Full pathnames of LLVM C/C++ front-end 'cc1' and 'cc1plus' binaries:
LLVMGCC  := 
LLVMGXX  := 
LLVMCC1  := 
LLVMCC1PLUS := 
LLVMGCC_LANGS := 
LLVMGCC_DRAGONEGG := 

# Information on Clang, if configured.
CLANGPATH := 
CLANGXXPATH := 
ENABLE_BUILT_CLANG := 1

# The LLVM capable compiler to use.
LLVMCC_OPTION := clang

# The flag used to emit LLVM IR.
LLVMCC_EMITIR_FLAG = -emit-llvm
LLVMCC_DISABLEOPT_FLAGS := -mllvm -disable-llvm-optzns

ifdef TARGET_LLVMGCC
LLVMGCC := $(TARGET_LLVMGCC)
LLVMCC := $(TARGET_LLVMGCC)
LLVMCC_OPTION := llvm-gcc
endif

ifdef TARGET_LLVMGXX
LLVMGXX := $(TARGET_LLVMGXX)
LLVMCXX := $(TARGET_LLVMGXX)
LLVMCC_OPTION := llvm-gcc
endif

ifdef TARGET_LLVMGCCARCH
LLVMGCCARCH := $(TARGET_LLVMGCCARCH)
endif

ifeq ($(ARCH),THUMB)
TEST_TARGET_FLAGS += -mthumb
endif

#
# Provide variables specific to llvm-test
#

# SPEC benchmarks:
#     If these are set then run the SPEC benchmarks.
#     You must provide the SPEC benchmarks on your own.




# Path to the SPEC benchmarks.
SPEC2006_ROOT := 
SPEC2000_ROOT := 
SPEC95_ROOT := 

# F2C: Enable LLVM to run Fortran benchmarks without a Fortran front-end

F2C_DIR := 
F2C     := 
F2C_INC := 
F2C_LIB := 

# F95: Enable LLVM to run Fortran benchmarks without a Fortran front-end

F95_DIR := 
F95     := 
F95_INC := 
F95_LIB := 

# Path to the Povray source code.

POVRAY_ROOT := 

# Path to the Namd source code

NAMD_ROOT := 

# Path to the Sweep3d source code

SWEEP3D_ROOT := 

# Path to the fpgrowth source code

FPGROWTH_ROOT := 

# Path to the ALP source code

ALP_ROOT := 

# Path to the NURBS source code

NURBS_ROOT := 

# Path to the HMMER source code

HMMER_ROOT := 

# Path to the Skidmarks source code

SKIDMARKS10_ROOT := 

# Disable LLC diffs for testing.


# Define HAVE_RE_COMP to 1 if re_comp is found, don't define it otherwise
HAVE_RE_COMP:=1

# Get the shared library (dll) extension
SHLIBEXT = .so
